{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 104857600,
      "rowLimit": 1000
     },
     "inputWidgets": {},
     "nuid": "1ef41d04-2d9f-4d69-966b-5a37043bbf30",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "SELECT \n",
    "  `Transaction ID`,\n",
    "  CAST(Date AS DATE) AS date,\n",
    "  `Customer ID`,\n",
    "  Gender,\n",
    "  Age,\n",
    "  CASE \n",
    "    WHEN Age < 25 THEN 'Under 25'\n",
    "    WHEN Age BETWEEN 25 AND 34 THEN '25-34'\n",
    "    WHEN Age BETWEEN 35 AND 44 THEN '35-44'\n",
    "    WHEN Age BETWEEN 45 AND 54 THEN '45-54'\n",
    "    ELSE '55+'\n",
    "  END AS age_group,\n",
    "  `Product Category`,\n",
    "  Quantity,\n",
    "  `Price per Unit`,\n",
    "  `Total Amount`,\n",
    "  DATE_TRUNC('month', CAST(Date AS DATE)) AS month\n",
    "FROM sales.default.sales_retail_dataset\n",
    "--KPI Summary (For Counter Widgets)\n",
    "SELECT \n",
    "  SUM(`Total Amount`) AS total_revenue,\n",
    "  COUNT(*) AS total_transactions,\n",
    "  COUNT(DISTINCT `Customer ID`) AS unique_customers,\n",
    "  AVG(`Total Amount`) AS avg_transaction_value,\n",
    "  SUM(Quantity) AS total_quantity_sold,\n",
    "  AVG(Quantity) AS avg_items_per_transaction\n",
    "FROM sales.default.sales_retail_dataset\n",
    "-- Revenue by Product Category (Bar Chart)\n",
    "SELECT \n",
    "  `Product Category` AS product_category,\n",
    "  SUM(`Total Amount`) AS total_revenue,\n",
    "  COUNT(*) AS total_transactions,\n",
    "  SUM(Quantity) AS total_quantity_sold\n",
    "FROM sales.default.sales_retail_dataset\n",
    "GROUP BY `Product Category`\n",
    "ORDER BY total_revenue DESC\n",
    "--Revenue Trend Over Time (Line Chart)\n",
    "SELECT \n",
    "  DATE_TRUNC('month', CAST(Date AS DATE)) AS month,\n",
    "  SUM(`Total Amount`) AS total_revenue,\n",
    "  COUNT(*) AS total_transactions\n",
    "FROM sales.default.sales_retail_dataset\n",
    "GROUP BY DATE_TRUNC('month', CAST(Date AS DATE))\n",
    "ORDER BY month\n",
    "--Sales by Gender (Pie Chart)\n",
    "SELECT \n",
    "  Gender,\n",
    "  SUM(`Total Amount`) AS total_revenue,\n",
    "  COUNT(*) AS total_transactions,\n",
    "  COUNT(DISTINCT `Customer ID`) AS unique_customers\n",
    "FROM sales.default.sales_retail_dataset\n",
    "GROUP BY Gender\n",
    "--Revenue by Age Group (Bar Chart)\n",
    "SELECT \n",
    "  CASE \n",
    "    WHEN Age < 25 THEN 'Under 25'\n",
    "    WHEN Age BETWEEN 25 AND 34 THEN '25-34'\n",
    "    WHEN Age BETWEEN 35 AND 44 THEN '35-44'\n",
    "    WHEN Age BETWEEN 45 AND 54 THEN '45-54'\n",
    "    ELSE '55+'\n",
    "  END AS age_group,\n",
    "  SUM(`Total Amount`) AS total_revenue,\n",
    "  COUNT(*) AS total_transactions\n",
    "FROM sales.default.sales_retail_dataset\n",
    "GROUP BY \n",
    "  CASE \n",
    "    WHEN Age < 25 THEN 'Under 25'\n",
    "    WHEN Age BETWEEN 25 AND 34 THEN '25-34'\n",
    "    WHEN Age BETWEEN 35 AND 44 THEN '35-44'\n",
    "    WHEN Age BETWEEN 45 AND 54 THEN '45-54'\n",
    "    ELSE '55+'\n",
    "  END\n",
    "ORDER BY \n",
    "  CASE age_group\n",
    "    WHEN 'Under 25' THEN 1\n",
    "    WHEN '25-34' THEN 2\n",
    "    WHEN '35-44' THEN 3\n",
    "    WHEN '45-44' THEN 4\n",
    "    ELSE 5\n",
    "  END\n",
    "--Product Category Performance Table\n",
    "SELECT \n",
    "  `Product Category` AS product_category,\n",
    "  SUM(`Total Amount`) AS total_revenue,\n",
    "  COUNT(*) AS total_transactions,\n",
    "  SUM(Quantity) AS total_quantity_sold,\n",
    "  AVG(`Total Amount`) AS avg_transaction_value,\n",
    "  COUNT(DISTINCT `Customer ID`) AS unique_customers\n",
    "FROM sales.default.sales_retail_dataset\n",
    "GROUP BY `Product Category`\n",
    "ORDER BY total_revenue DESC\n",
    "--Customer Repeat Purchase Analysis\n",
    "SELECT \n",
    "  `Customer ID`,\n",
    "  COUNT(*) AS purchase_count,\n",
    "  SUM(`Total Amount`) AS customer_lifetime_value,\n",
    "  MIN(CAST(Date AS DATE)) AS first_purchase_date,\n",
    "  MAX(CAST(Date AS DATE)) AS last_purchase_date\n",
    "FROM sales.default.sales_retail_dataset\n",
    "GROUP BY `Customer ID`\n",
    "ORDER BY customer_lifetime_value DESC\n",
    "\n",
    "\n",
    "\n",
    "SELECT * FROM `sales1`.`default`.`retail_sales_dataset_1` limit 100;\n",
    "\n",
    "\n",
    "SELECT*\n",
    "FROM sales1.default.retail_sales_dataset_1\n",
    "LIMIT 100;\n",
    "\n",
    "SELECT \n",
    "  MIN(`Age`) AS min_age,\n",
    "  MAX(`Age`) AS max_age,\n",
    "  AVG(`Age`) AS mean_age\n",
    "FROM sales1.default.retail_sales_dataset_1\n",
    "\n",
    "SELECT COUNT(*) AS number_of_rows,\n",
    "FROM sales1.default.retail_sales_dataset_1\n",
    "\n",
    "SELECT DISTINCT \n",
    "CASE \n",
    "  WHEN `Age` = '0' THEN 'Infant'\n",
    "  WHEN `Age`BETWEEN 1 AND 12 THEN 'Kids'\n",
    "  WHEN `Age`BETWEEN 13 AND 17 THEN 'Youth'\n",
    "  WHEN `Age`BETWEEN 18 AND 35 THEN 'Young Adult'\n",
    "  WHEN `Age`BETWEEN 36 AND 50 THEN 'Adults'\n",
    "  WHEN `Age`>50 AND `Age`<=60 THEN 'Elder'\n",
    "  WHEN `Age`>64 THEN 'Pensioner'\n",
    "END AS ethnicity\n",
    "FROM sales1.default.retail_sales_dataset_1;\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace",
     "schema": "default"
    }
   },
   "notebookName": "SALES_RETAIL DATASET.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
